export const systems = [
  { id: "overview", code: "00", name: "Complete product", short: "System architecture", summary: "A modular solar, wind, water and storage appliance coordinated by the local WELOS OS." },
  { id: "controller", code: "01", name: "Control core", short: "WELOS OS", summary: "Local, offline-first control with metering, safety interlocks and secure telemetry." },
  { id: "solar", code: "02", name: "Solar + catchment", short: "Energy and rain", summary: "A photovoltaic canopy produces power while its perimeter gutter captures rainfall." },
  { id: "wind", code: "03", name: "Urban wind", short: "Low-noise VAWT", summary: "A compact vertical-axis rotor supplements solar when a measured site resource supports it." },
  { id: "water", code: "04", name: "Water system", short: "Treat and store", summary: "First flush, filtration, UV, storage and pumping turn captured rain into a monitored utility supply." },
  { id: "storage", code: "05", name: "Energy core", short: "Store and route", summary: "MPPT, rectification, LiFePO4 storage and a hybrid inverter form the protected DC energy bus." },
];

const part = (id, system, code, name, category, role, evidence, status) => ({ id, system, code, name, category, role, evidence, status });

export const parts = [
  part("enclosure", "controller", "C01", "IP-rated enclosure", "Mechanical", "Protects low-voltage control and protection hardware from dust, water and accidental contact.", "Serviceable wall cabinet", "Ingress, thermal and structural ratings require prototype validation."),
  part("backplate", "controller", "C02", "Grounded backplate", "Safety", "Provides the bonded mounting plane for DIN-rail devices and cable segregation.", "Bonded metal mounting plate", "Earthing design must be reviewed to the installation standard."),
  part("controller-pcb", "controller", "C03", "WELOS edge controller", "Control", "Runs the deterministic supervisory state machine, logs telemetry and remains operational without cloud access.", "ESP32-S3 reference firmware", "Custom PCB, watchdog and production test fixture remain to be engineered."),
  part("energy-meter", "controller", "C04", "Bidirectional energy meter", "Measurement", "Measures generation, load, import and export for optimization and reporting.", "Modbus meter interface", "Meter accuracy class and certification are market-specific."),
  part("protection", "controller", "C05", "Safety and isolation rail", "Safety", "Holds breakers, fuses, surge protection, residual-current protection and safety contactors.", "Independent hardwired protection layer", "Device ratings and coordination require a licensed electrical engineer."),
  part("communications", "controller", "C06", "Communications gateway", "Telemetry", "Provides Ethernet, Wi-Fi and optional cellular backhaul with local API access.", "Offline-first gateway", "Secure element, certificates and carrier module remain product selections."),
  part("terminal-blocks", "controller", "C07", "Field I/O terminals", "Electrical", "Separates power, sensor, actuator and communications wiring into labelled service connections.", "Segregated terminal rail", "Final connector families depend on voltage and current ratings."),
  part("thermal-management", "controller", "C08", "Thermal management", "Reliability", "Monitors cabinet temperature and adds filtered ventilation when passive cooling is insufficient.", "Temperature sensor and fan", "Climate chamber and enclosure heat-load testing are required."),
  part("pv-array", "solar", "S01", "Photovoltaic canopy", "Generation", "Converts solar irradiance into DC electricity and provides the rain-catching surface.", "Six-module concept array", "Module count, wind loading, yield and shading require site engineering."),
  part("pv-racking", "solar", "S02", "Structural racking", "Mechanical", "Transfers panel and environmental loads into the base structure while maintaining drainage fall.", "Aluminium rail concept", "Stamped structural analysis and corrosion review are required."),
  part("rain-gutter", "solar", "S03", "Perimeter rain gutter", "Water", "Collects runoff from the panel canopy and directs it to the first-flush stage.", "Integrated catchment channel", "Hydraulic capacity must be checked against local design rainfall."),
  part("soiling-sensor", "solar", "S04", "Soiling reference sensor", "Measurement", "Compares a clean reference cell with the exposed canopy to detect dust losses and schedule maintenance.", "Reference-cell and irradiance concept", "Thresholds need calibration against local dust and weather."),
  part("cleaning-manifold", "solar", "S05", "Low-flow cleaning manifold", "Maintenance", "Directs approved water across the panels when the controller permits a safe cleaning cycle.", "Valved spray rail concept", "Nozzle coverage, water use and electrical separation require prototype testing."),
  part("vawt-rotor", "wind", "W01", "Helical VAWT rotor", "Generation", "Accepts wind from any direction without a yaw mechanism and drives the permanent-magnet generator.", "Low-solidity concept rotor", "Noise, fatigue, overspeed and measured site yield require testing."),
  part("wind-generator", "wind", "W02", "Permanent-magnet generator", "Electrical", "Converts rotor torque into variable-frequency three-phase electrical power.", "Direct-drive PMSG concept", "Torque curve and thermal rating must be matched to the rotor."),
  part("wind-brake", "wind", "W03", "Brake and overspeed system", "Safety", "Stops the rotor for faults, extreme wind and service access independently of cloud control.", "Fail-safe brake interface", "A certified mechanical/electrical shutdown path is required."),
  part("first-flush", "water", "R01", "First-flush diverter", "Water quality", "Rejects the initial roof runoff carrying concentrated dust and debris.", "Automatic diversion chamber", "Diversion volume must follow catchment area and local water guidance."),
  part("filter-train", "water", "R02", "Filter and UV train", "Treatment", "Uses sediment and carbon filtration followed by UV disinfection for the intended non-potable supply.", "Three-stage treatment concept", "Water testing defines treatment; potable use needs separate certification."),
  part("water-tank", "water", "R03", "Protected storage tank", "Storage", "Stores treated rainwater with screened vent, overflow and drain connections.", "Opaque tank with level monitoring", "Capacity, foundation and hygiene controls require site design."),
  part("water-pump", "water", "R04", "Variable-speed pump", "Hydraulics", "Supplies irrigation, cleaning or other approved non-potable loads on demand.", "Pressure-controlled pump", "Duty point, dry-run and backflow protection must be specified."),
  part("water-sensors", "water", "R05", "Level and quality sensors", "Measurement", "Measures tank level, flow, pressure, turbidity, conductivity and leak state for safe automation.", "Sensor manifold concept", "Sensor calibration and maintenance intervals require field validation."),
  part("mppt", "storage", "E01", "Solar MPPT charger", "Power electronics", "Tracks photovoltaic maximum power and converts it onto the protected DC bus.", "Independent MPPT stage", "Voltage window and current rating follow the final PV string design."),
  part("wind-rectifier", "storage", "E02", "Wind rectifier + dump load", "Power electronics", "Rectifies generator output and diverts surplus energy during battery or grid constraints.", "Brake resistor and controlled rectifier", "Thermal design must cover worst-case overspeed energy."),
  part("lifepo4-battery", "storage", "E03", "LiFePO4 battery pack", "Storage", "Stores renewable energy for evening use, outages and controlled peak reduction.", "Rack battery with BMS", "Capacity, fire strategy and market certification remain project-specific."),
  part("dc-bus", "storage", "E04", "Protected DC bus", "Electrical", "Combines sources through fused disconnects, current sensing, pre-charge and contactors.", "48 V nominal architecture", "Creepage, fault current and conductor sizing require detailed design."),
  part("hybrid-inverter", "storage", "E05", "Hybrid inverter/charger", "Power conversion", "Supplies AC loads, manages approved grid interaction and charges the battery when permitted.", "Bidirectional inverter interface", "A locally certified inverter and anti-islanding scheme are mandatory."),
  part("load-panel", "storage", "E06", "Critical-load panel", "Distribution", "Separates backed-up circuits from non-critical site loads and provides final branch protection.", "Essential-load distribution", "Circuit schedule and protective devices are installation-specific."),
];

export const partById = Object.fromEntries(parts.map((item) => [item.id, item]));
