export const softwareLayers = [
  {
    id: "runtime",
    code: "OS01",
    name: "Edge runtime",
    category: "On-device",
    role: "The ESP32-S3 executes a 250 ms local control cycle, supervises startup and uses a watchdog to recover from a stalled loop.",
    implementation: "firmware/src/main.cpp",
    boundary: "Runs on the device without the browser or an internet connection.",
  },
  {
    id: "io",
    code: "OS02",
    name: "Sensor and actuator I/O",
    category: "Field interface",
    role: "Reads solar, wind, battery, weather and water sensors; commands contactors, valves, pumps and the turbine brake through isolated drivers.",
    implementation: "firmware/src/HardwareIO.cpp",
    boundary: "Relay polarity, transducer calibration and safe output states require hardware validation.",
  },
  {
    id: "safety",
    code: "OS03",
    name: "Safety supervisor",
    category: "Control",
    role: "Checks emergency, BMS, inverter, leak and sensor faults before any operating or manual mode is applied.",
    implementation: "firmware/src/ControlEngine.cpp",
    boundary: "Required hardwired protection remains independent of software.",
  },
  {
    id: "optimizer",
    code: "OS04",
    name: "Resource optimizer",
    category: "Decision engine",
    role: "Routes renewable power to loads and battery, preserves reserve during outages, manages first flush and permits cleaning only within its weather and water limits.",
    implementation: "firmware/src/ControlEngine.cpp · src/control/engine.js",
    boundary: "Deterministic rules and limits can be explored in the browser simulator.",
  },
  {
    id: "api",
    code: "OS05",
    name: "Local device API",
    category: "Connectivity",
    role: "Exposes status and health locally; authenticated commands have a five-minute lease and cannot override interlocks.",
    implementation: "firmware/src/DeviceServer.cpp · docs/DEVICE_API.md",
    boundary: "Wi-Fi commissioning falls back to a device access point.",
  },
  {
    id: "console",
    code: "OS06",
    name: "Operator simulator",
    category: "Browser",
    role: "Shows modes, alarms, energy and water routing through clear-day, dust, storm and grid-outage scenarios.",
    implementation: "src/control/main.jsx · src/control/simulator.js",
    boundary: "A simulator for review and testing; the page does not command deployed hardware.",
  },
];
